CREATE TABLE IF NOT EXISTS pessoas (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(120) NOT NULL,
  email VARCHAR(160) UNIQUE NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS competencias (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(120) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS pessoa_competencia (
  pessoa_id BIGINT NOT NULL,
  competencia_id BIGINT NOT NULL,
  nivel INT NOT NULL,
  PRIMARY KEY (pessoa_id, competencia_id)
);
